In [6]:
import pandas as pd

data = pd.read_csv('data.csv')

data = data.dropna()
data

    ID First Name Last Name   Age Gender Department   Salary Date of Joining
0    1       John       Doe  25.0      M      Sales  50000.0        1/1/2020
1    2       Jane     Smith  30.0      F  Marketing  60000.0        6/1/2018
2    3        Bob   Johnson  45.0      M         HR  70000.0        9/1/2016
3    4      Alice  Williams  33.0      F         IT  80000.0        2/1/2017
4    5      James     Brown  27.0      M      Sales  55000.0        3/1/2019
7    8      Susan    Miller  42.0      F         IT  90000.0       11/1/2014
8    9      David    Wilson  28.0      M      Sales  60000.0        5/1/2020
9   10      Emily     Brown  35.0      F  Marketing  55000.0        4/1/2017
10  11       John       Doe  25.0      M      Sales  50000.0        1/1/2020
11  12       John       Doe  25.0      M      Sales  50000.0        1/1/2020

In [7]:
data = pd.read_csv('data.csv')
data

    ID First Name Last Name   Age Gender Department   Salary Date of Joining
0    1       John       Doe  25.0      M      Sales  50000.0        1/1/2020
1    2       Jane     Smith  30.0      F  Marketing  60000.0        6/1/2018
2    3        Bob   Johnson  45.0      M         HR  70000.0        9/1/2016
3    4      Alice  Williams  33.0      F         IT  80000.0        2/1/2017
4    5      James     Brown  27.0      M      Sales  55000.0        3/1/2019
5    6      Sarah       Lee   NaN      F  Marketing  65000.0       12/1/2018
6    7    Michael     Davis  39.0      M         HR      NaN        8/1/2015
7    8      Susan    Miller  42.0      F         IT  90000.0       11/1/2014
8    9      David    Wilson  28.0      M      Sales  60000.0        5/1/2020
9   10      Emily     Brown  35.0      F  Marketing  55000.0        4/1/2017
10  11       John       Doe  25.0      M      Sales  50000.0        1/1/2020
11  12       John       Doe  25.0      M      Sales  50000.0        1/1/2020

In [8]:
import pandas as pd

data = pd.read_csv('data.csv')

data['Age'].fillna(data['Age'].mean(), inplace=True)
data

,ID,First Name,Last Name,Age,Gender,Department,Salary,Date of Joining
0,1,John,Doe,25.000000,M,Sales,50000.0,1/1/2020
1,2,Jane,Smith,30.000000,F,Marketing,60000.0,6/1/2018
2,3,Bob,Johnson,45.000000,M,HR,70000.0,9/1/2016
3,4,Alice,Williams,33.000000,F,IT,80000.0,2/1/2017
4,5,James,Brown,27.000000,M,Sales,55000.0,3/1/2019
5,6,Sarah,Lee,32.181818,F,Marketing,65000.0,12/1/2018
6,7,Michael,Davis,39.000000,M,HR,NaN,8/1/2015
7,8,Susan,Miller,42.000000,F,IT,90000.0,11/1/2014
8,9,David,Wilson,28.000000,M,Sales,60000.0,5/1/2020
9,10,Emily,Brown,35.000000,F,Marketing,55000.0,4/1/2017
10,11,John,Doe,25.000000,M,Sales,50000.0,1/1/2020
11,12,John,Doe,25.000000,M,Sales,50000.0,1/1/2020